config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get '/product/result', to: 'products#result'

  get '/collection', to: 'collection_items#index'

  resources :products do
    resources :collection_items, except: [:index] do
    end
  end

  resources :stylist_clients

  root 'home#index'

  # Good Job dashboard
  authenticate :user, ->(user) { user.role === 'admin' } do
    mount GoodJob::Engine => 'good_job'
  end
end

app/models/collection_item.rb
class CollectionItem < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/controllers/collection_items_controller.rb
class CollectionItemsController < ApplicationController
  before_action :set_product, only: %i[ create new edit update ]

  def create
    create_params = { user_id: current_user.id }.merge(collection_item_params || {})

    @collection_item = @product.collection_items.create(create_params)

    redirect_to product_path(@product)
  end

  def new
    @collection_item = @product.collection_items.new
    @clients = StylistClient.where(stylist_id: current_user.id)
  end

  def index
    @products = Product.joins(:collection_items).where('user_id = ?', current_user.id)
  end

  def edit
    @collection_item = CollectionItem.find(params[:id])
    @clients = StylistClient.where(stylist_id: current_user.id)
  end

  def update
    @collection_item = CollectionItem.find(params[:id])

    respond_to do |format|
      if @collection_item.update(collection_item_params)
        format.html { redirect_to product_path(@product), notice: 'Collection Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @collection_item.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end

  def collection_item_params
    return unless params[:collection_item].present?

    params.require(:collection_item).permit(
      :user_id,
      # :category,
      # :color,
      palette: [],
      contrast: [],
      style: [],
      body_type: [],
      clients: []
    )
  end
end

app/helpers/collection_items_helper.rb
module CollectionItemsHelper
end

app/views/collection_items/_collection_item.html.erb
<div id="<%= dom_id collection_item %>">
  <% if collection_item.palette.length > 0 %>
    <p>
      <strong>Palette:</strong>
      <div class="flex">
        <% collection_item.palette.each do |palette| %>
          <div class="block m-2 p-2 text-sm bg-gray-700 text-white font-semibold rounded-full shadow-sm w-fit focus:bg-gray-700">
            <%= palette.titlecase %>
          </div>
        <% end %>
      </div>
    </p>
  <% end %>

  <% if collection_item.contrast.length > 0 %>
    <p>
      <strong>Contrast:</strong>
      <div class="flex">
        <% collection_item.contrast.each do |contrast| %>
          <div class="block m-2 p-2 text-sm bg-gray-700 text-white font-semibold rounded-full shadow-sm w-fit focus:bg-gray-700">
            <%= contrast.titlecase %>
          </div>
        <% end %>
      </div>
    </p>
  <% end %>

  <% if collection_item.style.length > 0 %>
    <p>
      <strong>Style:</strong>
      <div class="flex">
        <% collection_item.style.each do |style| %>
          <div class="block m-2 p-2 text-sm bg-gray-700 text-white font-semibold rounded-full shadow-sm w-fit focus:bg-gray-700">
            <%= style.titlecase %>
          </div>
        <% end %>
      </div>
    </p>
  <% end %>

  <% if collection_item.body_type.length > 0 %>
    <p>
      <strong>Body Type:</strong>
      <div class="flex">
        <% collection_item.body_type.each do |body_type| %>
          <div class="block m-2 p-2 text-sm bg-gray-700 text-white font-semibold rounded-full shadow-sm w-fit focus:bg-gray-700">
            <%= body_type.titlecase %>
          </div>
        <% end %>
      </div>
    </p>
  <% end %>

  <% if collection_item.clients.length > 0 %>
    <p>
      <strong>Clients:</strong>
      <div class="flex">
        <% collection_item.clients.each do |client| %>
          <div class="block m-2 p-2 text-sm bg-gray-700 text-white font-semibold rounded-full shadow-sm w-fit focus:bg-gray-700">
            <%= client.titlecase %>
          </div>
        <% end %>
      </div>
    </p>
  <% end %>
</div>

app/views/collection_items/_form.html.erb
<%=  form_with(model: [
    @product,
    @collection_item
  ] ) do |form| %>
  <div class="pb-4">
    <p class="block font-semibold text-gray-900 py-2">Color Palettes:</p>
    <div class="grid gap-2 grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6">
      <% PALETTES.each do |pal| %>
        <div>
          <%= form.check_box(:palette, { :multiple => true }, pal, nil) %>
          <%= form.label pal %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="pb-4">
    <p class="block font-semibold text-gray-900 py-2">Contrasts:</p>
    <div class="grid gap-2 grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6">
      <% CONTRASTS.each do |contrast| %>
        <div>
          <%= form.check_box :contrast, { :multiple => true }, contrast, nil %>
          <%= form.label contrast %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="pb-4">
    <p class="block font-semibold text-gray-900 py-2">Styles:</p>
    <div class="grid gap-2 grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6">
      <% STYLES.each do |style| %>
      <div>
        <%= form.check_box :style, { :multiple => true }, style, nil %>
        <%= form.label style %>
      </div>
      <% end %>
    </div>
  </div>

  <div class="pb-4">
    <p class="block font-semibold text-gray-900 py-2">Body Types:</p>
    <div class="grid gap-2 grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6">
      <% BODY_TYPES.each do |body_type| %>
      <div>
        <%= form.check_box :body_type, { :multiple => true }, body_type, nil %>
        <%= form.label body_type %>
      </div>
      <% end %>
    </div>
  </div>

  <div class="pb-4">
    <p class="block font-semibold text-gray-900 py-2">Who would look great on this:</p>
    <div class="grid gap-2 grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6">
      <% @clients.each do |client| %>
        <div>
          <%= form.check_box :clients, { :multiple => true }, client.name, nil %>
          <%= form.label client.name %>
        </div>
      <% end %>
    </div>

    <%= turbo_frame_tag "new_stylist_client" do %>
      <div class="pr-4 py-4"><%= link_to "New Client", new_stylist_client_path({ product: @product.id }), class: "link-primary" %></d>
    <% end %>
  </div>

  <ul class="py-4 flex items-center">
      <li class="pr-4"><%= form.submit 'Save to My Collection', class: "btn-primary" %></li>
      <li class="pr-4"><%= link_to 'Cancel', :back, class: "btn-secondary" %></li>
  </ul>
<% end %>

app/views/collection_items/edit.html.erb
<%= turbo_frame_tag "collection_item" do %>
  <h2>Who would look great on this?</h2>

  <%= render "form", collection_item: @collection_item %>
<%end%>

app/views/collection_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>My Collection</h1>

<ul class="flex py-4 flex-wrap">
  <li class="my-2 mr-4"><%= link_to "Home", root_path, class: 'link-primary' %></li>
  <li class="my-2 mr-4"><%= link_to "New product", new_product_path, class: 'link-primary' %></li>
  <li class="my-2 mr-4"><%= link_to "All products", products_path, class: 'link-primary' %></li>
</ul>

<main id="products">
  <div class="grid gap-3 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
    <% @products.each do |product| %>
      <div class="p-4 my-4">
        <%# <%= render product %>
        <%= render(ProductCardComponent.new(product: product)) %>

        <%= render product.collection_items.find_by(user_id: current_user.id ) %>
        <div>
          <%= link_to "Show this item", product, class: 'link-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</main>

app/views/collection_items/new.html.erb
<%= turbo_frame_tag "collection_item" do %>
  <h2>Who would look great on this?</h2>

  <%= render "form", collection_item: @collection_item %>
<%end %>