config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get '/product/result', to: 'products#result'

  get '/collection', to: 'collection_items#index'

  resources :products do
    resources :collection_items, except: [:index] do
    end
  end

  resources :stylist_clients

  root 'home#index'

  # Good Job dashboard
  authenticate :user, ->(user) { user.role === 'admin' } do
    mount GoodJob::Engine => 'good_job'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render
  end
end

app/views/home/index.html.erb
<h1>LookManager</h1>

<div class="pb-4">
  <% if user_signed_in? %> 
    <div class="pb-2"><%= t('views.home.index.welcome', name: current_user.first_name ) %></div>
    <%= button_to t('views.home.index.sign_out_action'), destroy_user_session_path, method: :delete, class: 'btn-secondary' %> 
  <% else %>
    <%= button_to t('views.home.index.sign_in_action'), new_user_session_path %> 
  <% end %>
</div>

<ul class="flex py-4 flex-wrap">
  <li class="my-2 mr-4"><%= link_to t('views.home.index.links.new_product'), new_product_path, class: 'link-primary' %></li>
  <li class="my-2 mr-4"><%= link_to t('views.home.index.links.all_products'), products_path, class: 'link-primary' %></li>
  <li class="my-2 mr-4"><%= link_to t('views.home.index.links.my_collection'), collection_path, class: 'link-primary' %></li>
  <% if current_user.role === 'admin' %>
    <li class="my-2 mr-4"><%= link_to "Good Job Dashboard", good_job_path, class: 'link-primary' %></li>
  <% end %>
</ul>