config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get '/product/result', to: 'products#result'

  get '/collection', to: 'collection_items#index'

  resources :products do
    resources :collection_items, except: [:index] do
    end
  end

  resources :stylist_clients

  root 'home#index'

  # Good Job dashboard
  authenticate :user, ->(user) { user.role === 'admin' } do
    mount GoodJob::Engine => 'good_job'
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :collection_items, dependent: :destroy
  has_many :users, through: :collection_items
  has_many :product_variants, dependent: :destroy

  def self.bulk_existing_urls(urls)
    Product.where(url: urls).pluck(:url)
  end
    
  include PgSearch::Model
  pg_search_scope :search,
                against: {
                  name: 'A',
                  brand: 'A',
                  store: 'A',
                  description: 'B',
                },
                using: {
                  tsearch: {
                    prefix: true,
                    dictionary: 'portuguese',
                    tsvector_column: 'searchable'
                  },
                  trigram: {
                    word_similarity: true
                  }
                },
                ignoring: :accents
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include Pagy::Backend

  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    items_per_page = 24

    # TODO: make this not-male filter dynamic and add other filters
    if params[:search].present? && params[:search] != ''
      @pagy, @products = pagy((Product.search(params[:search])
        .joins(:product_variants)
        .where(:product_variants => { :deleted_source => false })
        .where.not(gender: 'male')
        .or(Product.where('gender is null'))
        ), items: items_per_page)
      @count = Product.search(params[:search])
        .joins(:product_variants)
        .where(:product_variants => { :deleted_source => false })
        .where.not(gender: 'male')
        .or(Product.where('gender is null'))
        .count
    else
      @pagy, @products = pagy((Product
          .joins(:product_variants)
          .where(:product_variants => { :deleted_source => false })
          .where.not(gender: 'male')
          .or(Product.where('gender is null'))
          ), items: items_per_page)
      @count = Product
        .joins(:product_variants)
        .where(:product_variants => { :deleted_source => false })
        .where.not(gender: 'male')
        .or(Product.where('gender is null'))
        .count
    end
  end

  # GET /products/1 or /products/1.json
  def show
    id = params[:id]
    variant_title = params[:variant]
    @product = Product.find(id)
    
    if variant_title.present?
      @variant = ProductVariant.find_by(product_id: id, title: variant_title)
    else
      @variant = @product.product_variants.first
    end

    return @product, @variant
  end

  # GET /products/new
  def new
    # @product = Product.new
    @product_url = params[:product_url]
    return unless @product_url.present?

    @variant = ProductVariant.find_by(url: @product_url)
    @product = @variant.product if @variant.present?

    # If the product is already in the database, redirect to the result page and pass the product data
    if @product.present?
      redirect_to product_path(id: @product.id)
      return
    end

    # If the product is not on the database, start the scraping process
    scraper = Scrapers::ProductScraper.new(@product_url)
    scraped_product, scraped_variants = scraper.scrape

    ActiveRecord::Base.transaction do
      # check if the product is already in the database
      @product = Product.find_by(
        store: scraped_product["store"],
        sku: scraped_product["sku"]
      )
      
      @product = Product.create(scraped_product) if @product.nil?
      
      for variant in scraped_variants
        variant[:product_id] = @product.id

        existing_variant = ProductVariant.find_by(
          product_id: variant[:product_id],
          sku: variant[:sku]
        )

        if existing_variant.present?
          ProductVariant.update(existing_variant.id, variant)
        else
          ProductVariant.create(variant)
        end
      end
    end


    # Redirect to the result page and pass the scraped data
    redirect_to product_path(id: @product.id)
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(
      :search,
      :name,
      :sku,
      :brand,
      :store,
      :url,
      :store_url,
      :description,
      :gender,
      :currency,
      :old_price,
      :price,
      :installment_quantity,
      :installment_value,
      :available,
      images: [],
      sizes: [],
    )
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  include Pagy::Frontend

  def get_new_urls_from_products(urls)
    existing_urls = Product.bulk_existing_urls(urls)

    new_urls = urls - existing_urls

    return new_urls
  end
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <div class="relative mt-2 mb-4 rounded-md">
      <%= form.text_field :name, class: 'block w-full md:w-96 rounded-md border-0 py-1.5 pl-4 pr-4 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
    </div>
  </div>

  <div>
    <%= form.label :sku %>
    <div class="relative mt-2 mb-4 rounded-md">
      <%= form.text_field :sku, class: 'block w-full md:w-96 rounded-md border-0 py-1.5 pl-4 pr-4 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
    </div>
  </div>

  <div>
    <%= form.label :brand %>
    <div class="relative mt-2 mb-4 rounded-md">
      <%= form.text_field :brand, class: 'block w-full md:w-96 rounded-md border-0 py-1.5 pl-4 pr-4 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
    </div>
  </div>

  <div>
    <%= form.label :store %>
    <div class="relative mt-2 mb-4 rounded-md">
      <%= form.text_field :store, class: 'block w-full md:w-96 rounded-md border-0 py-1.5 pl-4 pr-4 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
    </div>
  </div>

  <div>
    <%= form.label :url %>
    <div class="relative mt-2 mb-4 rounded-md">
      <%= form.text_field :url, class: 'block w-full md:w-96 rounded-md border-0 py-1.5 pl-4 pr-4 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
    </div>
  </div>

  <div>
    <%= form.label :store_url %>
    <div class="relative mt-2 mb-4 rounded-md">
      <%= form.text_field :store_url, class: 'block w-full md:w-96 rounded-md border-0 py-1.5 pl-4 pr-4 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
    </div>

  <div>
    <%= form.label :description %>
    <div class="relative mt-2 mb-4 rounded-md">
      <%= form.text_area :description, class: 'block w-full md:w-96 rounded-md border-0 py-1.5 pl-4 pr-4 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
    </div>
  </div>

  <div>
    <%= form.label :old_price %>
    <div class="relative mt-2 mb-4 rounded-md">
      <%= form.text_field :old_price, class: 'block w-full md:w-96 rounded-md border-0 py-1.5 pl-4 pr-4 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
    </div>
  </div>

  <div>
    <%= form.label :price %>
    <div class="relative mt-2 mb-4 rounded-md">
      <%= form.text_field :price, class: 'block w-full md:w-96 rounded-md border-0 py-1.5 pl-4 pr-4 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
    </div>
  </div>

  <div>
    <%= form.label :installment_quantity %>
    <div class="relative mt-2 mb-4 rounded-md">
      <%= form.text_field :installment_quantity, class: 'block w-full md:w-96 rounded-md border-0 py-1.5 pl-4 pr-4 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
    </div>
  </div>

  <div>
    <%= form.label :installment_value %>
    <div class="relative mt-2 mb-4 rounded-md">
      <%= form.text_field :installment_value, class: 'block w-full md:w-96 rounded-md border-0 py-1.5 pl-4 pr-4 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
    </div>
  </div>

  <div class="pb-4 flex align-center">
    <%= form.label :available, class: 'pr-4' %>
    <%= form.check_box :available%>
  </div>

  <div class="py-2">
    <%= form.submit class: 'btn-primary' %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <div class="grid gap-1 grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6 p-2 my-4 bg-gray-50 drop-shadow">
    <% product.images.each do |image| %>
      <img src="<%= image %>" >
    <% end %>
  </div>

  <p class="text-sm font-medium text-gray-700">
    <%= link_to product.store.upcase, "https://#{product.store_url}", :target => "_blank", class: 'underline underline-offset-4 hover:text-gray-500' %> • <%= product.brand.upcase %>
  </p>
  <h3 class="pb-1 text-xl text-semibold underline underline-offset-4 text-gray-950 hover:text-gray-500">
    <%= link_to product.name, product.url, :target => "_blank" %>
  </h3>

  <div class="pb-1">
    <% if product.old_price.present? %>
      <span class="line-through"><%= product.currency %> <%= product.old_price %></span> <br />
    <% end %>

    <span class="font-medium"><%= product.currency %> <%= product.price %></span> <br />

    <span class="font-light text-sm">(<%= product.installment_quantity %>x of <%= product.currency %> <%= product.installment_value %>)</span>
  </div>

  <p class="pb-1">
    <strong>Last updated:</strong>
    <%= time_ago_in_words(product.updated_at) + " ago" %>
  </p>

  <p class="pb-1">
    <strong>Sku:</strong>
    <%= product.sku %>
  </p>

  <p class="pb-1">
    <strong>Description:</strong>
    <%= simple_format(product.description) %>
  </p>

  <p class="pb-1">
    <strong>Available:</strong>
    <%= product.available ? "Yes" : "No" %>
  </p>

  <%# # TODO: Add sizes %>
  <% if product.sizes.length > 0 %>
    <div class="pb-1">
      <strong>Sizes:</strong>
      <ul class="flex flex-wrap gap-1">
        <% product.sizes.each do |size| %>
          <li class="pr-4"><%= link_to size['size'] + ": " + (size['available'] ? "Available" : "Not Available"), "https://"+size['url'], target: '_blank', class: "link-primary" %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div class="flex py-2 flex-wrap">
  <div class="my-2"><%= link_to "Show this product", @product, class: 'link-primary' %></div>
  <div class="my-2 ml-4"><%= link_to "Back to products", products_path, class: 'link-primary' %></div>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= t('views.products.index.title') %></h1>

<ul class="flex py-4 flex-wrap">
  <li class="my-2 mr-4"><%= link_to t('views.products.index.links.home'), root_path, class: 'link-primary' %></li>
  <li class="my-2 mr-4"><%= link_to t('views.products.index.links.new_product'), new_product_path, class: 'link-primary' %></li>
  <li class="my-2 mr-4"><%= link_to t('views.products.index.links.my_collection'), collection_path, class: 'link-primary' %></li>
</ul>

<%= form_tag(products_path, method: 'get') do |f| %>
  <div>
    <%= label_tag :search, t('views.products.index.input.label') %>
    <div class="relative mt-2 rounded-md">
      <%= text_field_tag :search, params[:search], placeholder: t('views.products.index.input.placeholder'), class: 'block w-full rounded-md border-0 py-1.5 pl-4 pr-4 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
    </div>
  </div>
  <ul class="flex items-center py-2">
    <li class="my-2 mr-4"><%= submit_tag t('views.products.index.search_action'), class: 'btn-primary' %></li>
    <li class="my-2 mr-4"><%= link_to t('views.products.index.clear_action'), products_path, class: 'link-primary' %></li>
  </ul>
<% end %>

<main id="products">
  <p class="text-sm font-medium text-gray-900">
    <% if @products.count == 0 %>
      <%= t('views.products.index.no_results') %>
    <% else %>
      <%= t('views.products.index.results.showing', count: @products.count) %> <%= t('views.products.index.results.total', count: @count) %>
    <% end %>
  </p>

  <div class="w-fit mx-auto my-4"><%== pagy_nav(@pagy) %></div>

  <div class="grid gap-3 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
    <% @products.each do |product| %>
      <%= render(ProductCardComponent.new(product: product)) %>
    <% end %>
  </div>

  <div class="w-fit mx-auto my-4"><%== pagy_nav(@pagy) %></div>
</main>

app/views/products/new.html.erb
<h1><%= t('views.products.new.title') %></h1>

<%= form_tag('/products/new', method: 'get') do |f| %>
  <div>
    <%= label_tag 'product_url', t('views.products.new.input.label') %>
    <div class="relative mt-2 rounded-md">
      <%= url_field_tag 'product_url', nil, placeholder: t('views.products.new.input.placeholder'), class: 'block w-full rounded-md border-0 py-1.5 pl-4 pr-4 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
    </div>
  </div>
  <div class="py-2">
    <%= submit_tag t('views.products.new.action'), class: 'btn-primary' %>
  </div>
<% end %>

<br>

<div>
  <%= link_to t('views.products.new.links.back'), products_path, class: "link-primary" %>
</div>

  <%= link_to t('views.products.new.links.home'), root_path, class: "link-primary" %>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<!--
  This component uses @tailwindcss/forms and @tailwindcss/typography

  yarn add @tailwindcss/forms @tailwindcss/typography
  npm install @tailwindcss/forms @tailwindcss/typography

  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography')]

  @layer components {
    .no-spinner {
      -moz-appearance: textfield;
    }

    .no-spinner::-webkit-outer-spin-button,
    .no-spinner::-webkit-inner-spin-button {
      margin: 0;
      -webkit-appearance: none;
    }
  }
-->

<section>
  <div class="relative mx-auto max-w-screen-xl px-4 py-8">
    <div class="grid grid-cols-1 items-start gap-8 md:grid-cols-2">
      <div class="grid grid-cols-2 gap-4 md:grid-cols-1">
        <img
          alt="<%= @variant.title %>"
          src="<%= @variant.images.first %>"
          class="aspect-square w-full rounded-xl object-contain"
        />

        <div class="grid grid-cols-2 gap-4 lg:mt-4">
          <% @variant.images.drop(1).each do |image|%>
            <img
              alt="<%= @variant.title %>"
              src="<%= image %>"
              class="aspect-square w-full rounded-xl object-cover"
            />
          <% end %>
        </div>
      </div>

      <div class="sticky top-0">
        <strong class="text-xs font-medium">
          <%= t('views.products.show.last_updated', date: time_ago_in_words(@variant.updated_at)) %>
        </strong>
        <%# <strong
          class="rounded-full border border-blue-600 bg-gray-100 px-3 py-0.5 text-xs font-medium tracking-wide text-blue-600"
        >
          Pre Order
        </strong> %>

        <div class="mt-8 flex justify-between flex-col">
          <div class="max-w-[35ch] space-y-2 flex-auto">
            <p class="text-sm font-medium text-gray-700">
              <span><%= @product.store %></span> • <span><%= @product.brand %></span>
              <% if @product.gender.present? %>
                • <span><%= @product.gender == 'female' ? t('female') : t('male') %></span>
              <% end %>
            </p>

            <h1 class="text-xl font-bold sm:text-2xl">
              <%= @variant.full_name %>
            </h1>
            
            <% if @variant.sku.present? %><p class="text-xs"><%= @variant.sku %></p><% end %>

            <%# <p class="text-sm">Highest Rated Product</p>

            <div class="-ms-0.5 flex">
              <svg
                class="h-5 w-5 text-yellow-400"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
              >
                <path
                  d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                />
              </svg>

              <svg
                class="h-5 w-5 text-yellow-400"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
              >
                <path
                  d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                />
              </svg>

              <svg
                class="h-5 w-5 text-yellow-400"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
              >
                <path
                  d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                />
              </svg>

              <svg
                class="h-5 w-5 text-yellow-400"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
              >
                <path
                  d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                />
              </svg>

              <svg
                class="h-5 w-5 text-gray-200"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
              >
                <path
                  d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
                />
              </svg>
            </div> %>
          </div>

          <div class="flex flex-col justify-end py-2">
            <% if @variant.old_price %>
              <span class="text-gray-400 text-sm md:text-md line-through"><%= number_to_currency(@variant.old_price) %></span>
              <span class="text-gray-950 md:text-lg font-bold"><%= number_to_currency(@variant.price) %></span>
            <% else %>
              <span class="text-gray-950 md:text-lg font-bold"><%= number_to_currency(@variant.price) %></span>
            <% end %>
            
            <% if @variant.installment_value && @variant.installment_quantity %>
              <span class="text-gray-500 text-sm md:text-md"><%= t('views.products.show.price.installments', installments: @variant.installment_quantity, price: number_to_currency(@variant.installment_value)) %></span>
            <% end %>
          </div>
        </div>

        <div class="mt-4">
          <div class="prose max-w-none">
            <p>
              <%= simple_format(@variant.description) %>
            </p>
          </div>

          <%# <button class="mt-2 text-sm font-medium underline">Read More</button> %>
        </div>

        <div class="my-8">
            <% if @variant.sizes.count > 1 %>
              <legend class="mb-1 text-sm font-medium"><%= t('views.products.show.sizes') %></legend>

              <div class="flex flex-wrap gap-1">
                <% @variant.sizes.each do |size| %>
                  <div class='group relative inline-flex px-2 py-1 items-center justify-center rounded-full border text-xs font-medium <%= size["available"] ? "bg-black text-white" : "" %>'>
                    <span
                      class="absolute bottom-9 opacity-0 font-medium text-gray-950 transition ease-in-out duration-500 group-hover:opacity-100 bg-gray-50 py-1 px-3"
                    >
                      <%= size['available'] ? t('available') : t('not_available') %>
                    </span>

                    <%= size["size"].upcase %>
                  </div>
                <% end %>
              </div>
            <% end %>


          <% if @product.product_variants.count > 1 %>
            <div class="mt-4">
              <legend class="mb-1 text-sm font-medium"><%= t('views.products.show.options') %></legend>

              <div class="flex flex-wrap gap-1">
                <% @product.product_variants.each do |variant| %>
                  <%= button_to variant.title, product_path(id: @product.id), method: :get, params: { variant: variant.title }, class: "group inline-block rounded-full border px-3 py-1 text-xs font-medium #{'bg-black text-white' if variant.id == @variant.id}" %>
                <% end %>
              </div>
            </div>
          <% end %>

          <div class="mt-8">
            <%= link_to t('views.products.show.store_link', store: @product.store), "#{@variant.url}?ref=look-manager", target: '_blank', class: 'btn-primary' %>
          </div>
        </div>
        
        <%= turbo_frame_tag "collection_item" do %>
          <% unless @product.collection_items.find_by(user_id: current_user) %>
            <ul class="flex py-4 flex-wrap">
              <li class="pr-4"><%= link_to "Add to Collection", new_product_collection_item_path(@product, @product.collection_items.find_by(user_id: current_user)), class: "btn-primary" %></li>
              <li class="pr-4"><%= link_to "Back to products", products_path, "data-turbo-frame": "_top", class: "link-primary" %></li>
            </ul>
          <%end%>

          <% if @product.collection_items.find_by(user_id: current_user) %>
            <%= render @product.collection_items.find_by(user_id: current_user) %>
            
            <ul class="flex py-4 flex-wrap">
              <li class="pr-4"><%= link_to "Edit classification", edit_product_collection_item_path(@product, @product.collection_items.find_by(user_id: current_user)), class: "link-primary" %></li>
              <li class="pr-4"><%= link_to "Back to products", products_path, "data-turbo-frame": "_top", class: "link-primary" %></li>
              <li class="pr-4"><%= link_to "New product", new_product_path, "data-turbo-frame": "_top", class: 'link-primary' %></li>
            </ul>
          <%end%>
        <%end%>
      </div>
    </div>
  </div>
</section>